[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Use `probe-run --list-chips` to find yours
runner = "probe-run --chip STM32L432KCUx --connect-under-reset"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
